/**
 * @class EmitAssetsWebpackPlugin
 * A Webpack plugin that emits assets generated by the build
 * Used
 **/

module.exports = class EmitAssetsWebpackPlugin {
  constructor({ onEmit } = {}) {
    if (typeof onEmit !== 'function') {
      throw new Error('Missing required parameter onEmit of type function');
    }
    this.onEmit = onEmit;
  }
  apply(compiler) {
    compiler.plugin('emit', (compilation, callback) => {
      const assets = compilation.chunks.reduce((assets, chunk) => {
        assets[chunk.name] = chunk.files;
      }, {});
      this.onEmit({ assets, compilation });
      callback();
    });
  }
};
